//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leo.FrameWork.MeetingManageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cfldcn.com/meetingwebservices/", ConfigurationName="MeetingManageService.meetingManageServiceSoap")]
    public interface meetingManageServiceSoap {
        
        // CODEGEN: 命名空间 http://cfldcn.com/meetingwebservices/ 的元素名称 meetingInfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cfldcn.com/meetingwebservices/UrgeMeetingManage", ReplyAction="*")]
        Leo.FrameWork.MeetingManageService.UrgeMeetingManageResponse UrgeMeetingManage(Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cfldcn.com/meetingwebservices/UrgeMeetingManage", ReplyAction="*")]
        System.Threading.Tasks.Task<Leo.FrameWork.MeetingManageService.UrgeMeetingManageResponse> UrgeMeetingManageAsync(Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrgeMeetingManageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrgeMeetingManage", Namespace="http://cfldcn.com/meetingwebservices/", Order=0)]
        public Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequestBody Body;
        
        public UrgeMeetingManageRequest() {
        }
        
        public UrgeMeetingManageRequest(Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cfldcn.com/meetingwebservices/")]
    public partial class UrgeMeetingManageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string meetingInfo;
        
        public UrgeMeetingManageRequestBody() {
        }
        
        public UrgeMeetingManageRequestBody(string meetingInfo) {
            this.meetingInfo = meetingInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrgeMeetingManageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrgeMeetingManageResponse", Namespace="http://cfldcn.com/meetingwebservices/", Order=0)]
        public Leo.FrameWork.MeetingManageService.UrgeMeetingManageResponseBody Body;
        
        public UrgeMeetingManageResponse() {
        }
        
        public UrgeMeetingManageResponse(Leo.FrameWork.MeetingManageService.UrgeMeetingManageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cfldcn.com/meetingwebservices/")]
    public partial class UrgeMeetingManageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UrgeMeetingManageResult;
        
        public UrgeMeetingManageResponseBody() {
        }
        
        public UrgeMeetingManageResponseBody(string UrgeMeetingManageResult) {
            this.UrgeMeetingManageResult = UrgeMeetingManageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface meetingManageServiceSoapChannel : Leo.FrameWork.MeetingManageService.meetingManageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class meetingManageServiceSoapClient : System.ServiceModel.ClientBase<Leo.FrameWork.MeetingManageService.meetingManageServiceSoap>, Leo.FrameWork.MeetingManageService.meetingManageServiceSoap {
        
        public meetingManageServiceSoapClient() {
        }
        
        public meetingManageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public meetingManageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public meetingManageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public meetingManageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Leo.FrameWork.MeetingManageService.UrgeMeetingManageResponse Leo.FrameWork.MeetingManageService.meetingManageServiceSoap.UrgeMeetingManage(Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequest request) {
            return base.Channel.UrgeMeetingManage(request);
        }
        
        public string UrgeMeetingManage(string meetingInfo) {
            Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequest inValue = new Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequest();
            inValue.Body = new Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequestBody();
            inValue.Body.meetingInfo = meetingInfo;
            Leo.FrameWork.MeetingManageService.UrgeMeetingManageResponse retVal = ((Leo.FrameWork.MeetingManageService.meetingManageServiceSoap)(this)).UrgeMeetingManage(inValue);
            return retVal.Body.UrgeMeetingManageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Leo.FrameWork.MeetingManageService.UrgeMeetingManageResponse> Leo.FrameWork.MeetingManageService.meetingManageServiceSoap.UrgeMeetingManageAsync(Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequest request) {
            return base.Channel.UrgeMeetingManageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Leo.FrameWork.MeetingManageService.UrgeMeetingManageResponse> UrgeMeetingManageAsync(string meetingInfo) {
            Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequest inValue = new Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequest();
            inValue.Body = new Leo.FrameWork.MeetingManageService.UrgeMeetingManageRequestBody();
            inValue.Body.meetingInfo = meetingInfo;
            return ((Leo.FrameWork.MeetingManageService.meetingManageServiceSoap)(this)).UrgeMeetingManageAsync(inValue);
        }
    }
}
